[package]
name = "nouveau_sleep_daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
zbus = { version = "5", default-features = false, features = ["tokio"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
futures-lite = "2"
